# Test against this version of Jode.js
environment:
  matrix:
   # tell Appveyor we are using node.js version 6
  - nodejs_version: "6"

# Install scripts. (runs after repo cloning)
install:
  # get the latest stable verion of Node.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post-install test scripts
test_script:
  # output useful info for debugging
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build
build: off
